name: BuildAndTest-Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        working-directory: src
        run: dotnet build

      - name: Test
        working-directory: src
        run: 'dotnet test --no-build --verbosity normal --test-adapter-path:. --logger:"junit;LogFilePath=../artifacts/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
