name: InspectMaster

# Controls when the action will run. 
on: [push]

jobs:
  inspection:
   runs-on: ubuntu-latest # or macos-latest, windows-latest
   name: InspectCode
   steps:
         
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 5.0.x
         
    - name: Restore
      working-directory: src
      run: dotnet restore 
    
    - name: Inspect code
      uses: muno92/resharper_inspectcode@1.0.0
      with:
          solutionPath: './src/QnapBackupDecryptor.sln'
