name: ReleaseAll

# on:
#   release:
#     types: [published]

on: workflow_dispatch

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ["linux", "windows", "macOS"]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: BuildFrameworkDep
        shell: bash
        working-directory: src
        run: |
          tag=0.0.0
          #$(git describe --tags --abbrev=0)
          release_name="QnapBackupDecryptor-FD-$tag-${{ matrix.target }}"
          workspace="${${{ github.workspace }}//\\//}"   

          # Build everything
          dotnet publish ./QnapBackupDecryptor.Console/QnapBackupDecryptor.Console.csproj  -c Release -f net8.0 -r ${{ matrix.target }} --self-contained false -p:PublishSingleFile=true -p:PublishDir="${workspace}/releases/$release_name" -p:DebugType=None -p:DebugSymbols=false

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            mv ${workspace}/releases/$release_name/QnapBackupDecryptor.Console.exe ${workspace}/releases/$release_name/QnapBackupDecryptor.exe
            7z a -tzip "../${release_name}.zip" "${workspace}/releases/${release_name}/*"
          else
            mv ${workspace}/releases/$release_name/QnapBackupDecryptor.Console ${workspace}/releases/$release_name/QnapBackupDecryptor
            tar czvf "../${release_name}.tar.gz" ${workspace}/releases/$release_name
          fi

          # Delete output directory
          rm -r "${workspace}/releases/$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "QnapBackupDecryptor-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: BuildSelfContained
        shell: bash
        working-directory: src
        run: |
          tag=0.0.0 
          #$(git describe --tags --abbrev=0)
          release_name="QnapBackupDecryptor-SC-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish QnapBackupDecryptor.sln -c Release -f net8.0 -r ${{ matrix.target }} --self-contained true -p:PublishDir="${{ github.workspace }}/releases/$release_name" -p:DebugType=None -p:DebugSymbols=false

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "../${release_name}.zip" "${{ github.workspace }}/releases/${release_name}/*"
          else
            tar czvf "../${release_name}.tar.gz" "${{ github.workspace }}/releases/$release_name"
          fi

          # Delete output directory
          rm -r "${{ github.workspace }}/releases/$release_name"
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "QnapBackupDecryptor-*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
